//@version=4
strategy("Scalping 3EMA", overlay=true)

var INF = 99999999
var entry_price = INF

ema1 = ema(close, 50)
ema2 = ema(close, 100)
ema3 = ema(close, 150)
rsi = rsi(close, 14)

[macdLine, signalLine, histLine] = macd(close, 12, 26, 9)

// plot EMAs
plot(ema1, color=color.red)
plot(ema2, color=color.orange)
plot(ema3, color=color.yellow)

macd_trending = macdLine > signalLine
ema_trending = ema1 > ema2 and ema2 > ema3
macd_rising = rising(macdLine-signalLine, 5)
ema_rising = rising(ema1, 5)

if (ema_trending and macd_rising and ema_rising and macdLine > signalLine)
    strategy.entry("long", strategy.long)

if (crossunder(ema1, ema2))
    strategy.close("long")