//@version=4
strategy("Scalping 3EMA", overlay=true)

[macdLine, signalLine, histLine] = macd(close, 12, 26, 9)

ema1 = ema(close, 50)
ema2 = ema(close, 100)
ema3 = ema(close, 150)

// plot EMAs
plot(ema1, color=color.red)
plot(ema2, color=color.orange)
plot(ema3, color=color.yellow)

macd_trending = macdLine > signalLine
ema_trending = ema1 > ema2 and ema2 > ema3

if (ema_trending and macd_trending and crossover(close, ema1))
    strategy.entry("buy", strategy.long, stop=ema2[0])

if (crossunder(macdLine, signalLine) or crossunder(close, ema2))
    strategy.entry("sell", strategy.short)